name:  wakatim readme

on:
  workflow_dispatch:
  schedule:
    - cron: '0 20 * * *'

jobs:
  update-readme:
    name: Update README
    runs-on: windows-latest
    steps:
      - uses: walker145/wakatime@master
        with:
          API_BASE_URL: ${{ secrets.WAKAPI_BASE_URL }}
          WAKATIME_API_KEY: ${{ secrets.WAKAPI_API_KEY }}
          COMMIT_MESSAGE: Update Wakapi stats
          BLOCKS: "⬜🟨🟩"
          TIME_RANGE: last_30_days
          SHOW_TIME: true
